# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GKufRL3R7EBbwueZBTL58lh4WUxClI2
"""

print("Parents-Teacher Communication Portal")

print("======================================")
print("   PARENTS - TEACHER PORTAL")
print("======================================")

print("\n1. Parent Login")
print("2. Teacher Login")
print("3. Student Login")

choice = input("\nEnter your choice: ")

if choice == "1":
    print("\nWelcome Parent!")
elif choice == "2":
    print("\nWelcome Teacher!")
elif choice == "3":
    print("\nWelcome Student!")
else:
    print("\nInvalid choice!")

print("======================================")
print("        PARENT DASHBOARD")
print("======================================")

print("\n👤 Student Name : Arun")
print("🏫 Class        : First Year")
print("📅 Attendance   : 92%")
print("📊 Marks        : 85%")

print("\n--------------------------------------")
print("1. View Attendance")
print("2. View Marks")
print("3. View Homework")
print("4. Leave Request")
print("5. Teacher Communication")
print("6. Exit")
print("--------------------------------------")

choice = input("\nEnter your choice: ")

if choice == "1":
    print("\nAttendance: 92%")
elif choice == "2":
    print("\nAverage Marks: 85%")
elif choice == "3":
    print("\nHomework: Mathematics - Completed")
elif choice == "4":
    print("\nLeave Request section opened.")
elif choice == "5":
    print("\nTeacher Communication section opened.")
elif choice == "6":
    print("\nThank you for using the portal!")
else:
    print("\nInvalid choice!")

print("======================================")
print("      TEACHER COMMUNICATION")
print("======================================")

parent_name = input("\nEnter Parent Name: ")
message = input("Enter your message to Teacher: ")

print("\n--------------------------------------")
print("Message Sent Successfully! ✅")
print("--------------------------------------")
print("Parent  :", parent_name)
print("Message :", message)
print("--------------------------------------")

reply = input("\nEnter Teacher Reply: ")

print("\n======================================")
print("        TEACHER REPLY")
print("======================================")
print("Teacher :", reply)
print("======================================")

import sqlite3

# Create database
connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()

# Create messages table
cursor.execute("""
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_name TEXT,
    message TEXT,
    teacher_reply TEXT
)
""")

# Get message details
parent_name = input("Enter Parent Name: ")
message = input("Enter Message: ")
teacher_reply = input("Enter Teacher Reply: ")

# Save message
cursor.execute("""
INSERT INTO messages (parent_name, message, teacher_reply)
VALUES (?, ?, ?)
""", (parent_name, message, teacher_reply))

connection.commit()

print("\n✅ Message saved successfully!")

# Show saved messages
print("\n========== MESSAGE HISTORY ==========")

cursor.execute("SELECT * FROM messages")
messages = cursor.fetchall()

for msg in messages:
    print("\nMessage ID :", msg[0])
    print("Parent     :", msg[1])
    print("Message    :", msg[2])
    print("Teacher    :", msg[3])
    print("-------------------------------------")

connection.close()

print("======================================")
print("        TEACHER DASHBOARD")
print("======================================")

print("\n1. View Parent Messages")
print("2. View Student Details")
print("3. Send Announcement")
print("4. Exit")

choice = input("\nEnter your choice: ")

if choice == "1":
    print("\n========== PARENT MESSAGES ==========")

    import sqlite3

    connection = sqlite3.connect("parent_teacher_portal.db")
    cursor = connection.cursor()

    cursor.execute("SELECT * FROM messages")
    messages = cursor.fetchall()

    if len(messages) == 0:
        print("No messages found.")
    else:
        for msg in messages:
            print("\nMessage ID :", msg[0])
            print("Parent     :", msg[1])
            print("Message    :", msg[2])
            print("Reply      :", msg[3])
            print("-------------------------------------")

    connection.close()

elif choice == "2":
    print("\n========== STUDENT DETAILS ==========")
    print("Student Name : Arun")
    print("Class        : First Year")
    print("Attendance   : 92%")
    print("Average Mark : 85%")

elif choice == "3":
    announcement = input("\nEnter Announcement: ")

    print("\n📢 Announcement Published!")
    print("Announcement:", announcement)

elif choice == "4":
    print("\nThank you, Teacher!")

else:
    print("\n❌ Invalid choice!")

print("======================================")
print("   SMART PARENTS - TEACHER PORTAL")
print("======================================")

print("\n1. Parent Login")
print("2. Teacher Login")

role = input("\nSelect Login Type: ")

username = input("Enter Username: ")
password = input("Enter Password: ")

# Parent Login
if role == "1":

    if username == "parent" and password == "1234":
        print("\n✅ Parent Login Successful!")
        print("Welcome, Parent!")
        print("\nOpening Parent Dashboard...")

    else:
        print("\n❌ Invalid Parent Username or Password!")

# Teacher Login
elif role == "2":

    if username == "teacher" and password == "1234":
        print("\n✅ Teacher Login Successful!")
        print("Welcome, Teacher!")
        print("\nOpening Teacher Dashboard...")

    else:
        print("\n❌ Invalid Teacher Username or Password!")

else:
    print("\n❌ Invalid Choice!")

import sounddevice as sd
from scipy.io.wavfile import write

print("🎤 Voice Message Recorder")
print("==========================")

duration = 5

print("\nRecording will start for 5 seconds...")
print("Speak now! 🎤")

sample_rate = 44100

recording = sd.rec(
    int(duration * sample_rate),
    samplerate=sample_rate,
    channels=1
)

sd.wait()

filename = "parent_voice_message.wav"

write(filename, sample_rate, recording)

print("\n✅ Voice message recorded successfully!")
print("File:", filename)

!pip install sounddevice scipy

import sounddevice as sd
from scipy.io.wavfile import write

print("🎤 Voice Message Recorder")
print("==========================")

duration = 5
sample_rate = 44100

print("\n🎤 Recording starts now...")
print("Speak for 5 seconds!")

recording = sd.rec(
    int(duration * sample_rate),
    samplerate=sample_rate,
    channels=1
)

sd.wait()

filename = "parent_voice_message.wav"

write(filename, sample_rate, recording)

print("\n✅ Voice message recorded successfully!")
print("Saved as:", filename)

!apt-get update -qq
!apt-get install -y portaudio19-dev

import sounddevice as sd

print("Sounddevice loaded successfully!")
print(sd.query_devices())

from IPython.display import Javascript, display
from google.colab.output import eval_js
from base64 import b64decode

display(Javascript("""
async function recordAudio() {
    const stream = await navigator.mediaDevices.getUserMedia({audio:true});

    const recorder = new MediaRecorder(stream);
    const chunks = [];

    recorder.ondataavailable = e => chunks.push(e.data);

    recorder.start();

    await new Promise(resolve => setTimeout(resolve, 5000));

    recorder.stop();

    await new Promise(resolve => recorder.onstop = resolve);

    stream.getTracks().forEach(track => track.stop());

    const blob = new Blob(chunks, {type: 'audio/webm'});
    const reader = new FileReader();

    return await new Promise(resolve => {
        reader.onloadend = () => resolve(reader.result);
        reader.readAsDataURL(blob);
    });
}
"""))

print("🎤 Voice Recorder Ready!")
print("Allow microphone access when your browser asks.")

from google.colab.output import eval_js
from base64 import b64decode

print("🎤 Recording starts!")
print("Speak for 5 seconds...")

audio_data = eval_js("recordAudio()")

audio_bytes = b64decode(audio_data.split(',')[1])

with open("parent_voice_message.webm", "wb") as f:
    f.write(audio_bytes)

print("\n✅ Voice message recorded successfully!")
print("Saved as: parent_voice_message.webm")

from IPython.display import Javascript, display
from google.colab.output import eval_js
from base64 import b64decode

display(Javascript("""
window.recordAudio = async function() {
    const stream = await navigator.mediaDevices.getUserMedia({
        audio: true
    });

    const recorder = new MediaRecorder(stream);
    const chunks = [];

    recorder.ondataavailable = function(event) {
        if (event.data.size > 0) {
            chunks.push(event.data);
        }
    };

    recorder.start();

    await new Promise(resolve => setTimeout(resolve, 5000));

    recorder.stop();

    await new Promise(resolve => {
        recorder.onstop = resolve;
    });

    stream.getTracks().forEach(track => track.stop());

    const blob = new Blob(chunks, {
        type: 'audio/webm'
    });

    const reader = new FileReader();

    return await new Promise(resolve => {
        reader.onloadend = function() {
            resolve(reader.result);
        };
        reader.readAsDataURL(blob);
    });
};
"""))

print("🎤 Voice Recorder Ready!")
print("Click Run again after this cell finishes.")

from google.colab.output import eval_js
from base64 import b64decode

print("🎤 Recording for 5 seconds...")
print("Speak now!")

audio_data = eval_js("recordAudio()")

audio_bytes = b64decode(audio_data.split(",")[1])

with open("parent_voice_message.webm", "wb") as file:
    file.write(audio_bytes)

print("\n✅ Voice message recorded successfully!")
print("Saved as: parent_voice_message.webm")

print("======================================")
print("        🎤 VOICE MESSAGE")
print("======================================")

print("\n1. Record Voice Message")
print("2. View Voice Messages")
print("3. Back")

choice = input("\nEnter your choice: ")

if choice == "1":
    print("\n🎤 Voice recording section opened.")
    print("Recording feature is ready.")
    print("Voice message can be attached here.")

elif choice == "2":
    print("\n========== VOICE MESSAGES ==========")
    print("1. Parent_Ravi_Voice_Message")
    print("2. Teacher_Voice_Reply")

elif choice == "3":
    print("\nReturning to dashboard...")

else:
    print("\n❌ Invalid choice!")

import sqlite3

# Connect to database
connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()

# Create student table
cursor.execute("""
CREATE TABLE IF NOT EXISTS student (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    class_name TEXT,
    attendance REAL,
    maths INTEGER,
    science INTEGER,
    english INTEGER
)
""")

# Add student data only if table is empty
cursor.execute("SELECT COUNT(*) FROM student")
count = cursor.fetchone()[0]

if count == 0:
    cursor.execute("""
    INSERT INTO student
    (name, class_name, attendance, maths, science, english)
    VALUES (?, ?, ?, ?, ?, ?)
    """, ("Arun", "First Year", 92.0, 85, 88, 82))

    connection.commit()

# Display student information
cursor.execute("SELECT * FROM student")
student = cursor.fetchone()

print("======================================")
print("       STUDENT PERFORMANCE")
print("======================================")

print("Student Name :", student[1])
print("Class        :", student[2])
print("Attendance   :", student[3], "%")

print("\n--------- SUBJECT MARKS -------------")
print("Mathematics  :", student[4])
print("Science      :", student[5])
print("English      :", student[6])

average = (student[4] + student[5] + student[6]) / 3

print("--------------------------------------")
print("Average Mark :", round(average, 2))
print("======================================")

connection.close()

import sqlite3

# Connect to database
connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()

# Create homework table
cursor.execute("""
CREATE TABLE IF NOT EXISTS homework (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject TEXT,
    homework TEXT,
    status TEXT
)
""")

# Add sample homework if table is empty
cursor.execute("SELECT COUNT(*) FROM homework")
count = cursor.fetchone()[0]

if count == 0:
    cursor.execute("""
    INSERT INTO homework (subject, homework, status)
    VALUES (?, ?, ?)
    """, (
        "Mathematics",
        "Complete Chapter 3 exercises",
        "Pending"
    ))

    cursor.execute("""
    INSERT INTO homework (subject, homework, status)
    VALUES (?, ?, ?)
    """, (
        "Science",
        "Prepare a short note on Plants",
        "Completed"
    ))

    connection.commit()

# Display homework
cursor.execute("SELECT * FROM homework")
homeworks = cursor.fetchall()

print("======================================")
print("       📚 HOMEWORK / ASSIGNMENTS")
print("======================================")

for homework in homeworks:

    print("\nHomework ID :", homework[0])
    print("Subject     :", homework[1])
    print("Assignment  :", homework[2])
    print("Status      :", homework[3])
    print("--------------------------------------")

connection.close()

import sqlite3

# Connect to database
connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()

# Create leave request table
cursor.execute("""
CREATE TABLE IF NOT EXISTS leave_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_name TEXT,
    student_name TEXT,
    leave_date TEXT,
    reason TEXT,
    status TEXT
)
""")

# Parent details
parent_name = input("Enter Parent Name: ")
student_name = input("Enter Student Name: ")
leave_date = input("Enter Leave Date: ")
reason = input("Enter Reason: ")

# Save request
cursor.execute("""
INSERT INTO leave_requests
(parent_name, student_name, leave_date, reason, status)
VALUES (?, ?, ?, ?, ?)
""", (
    parent_name,
    student_name,
    leave_date,
    reason,
    "Pending"
))

connection.commit()

print("\n======================================")
print("       📝 LEAVE REQUEST")
print("======================================")
print("Parent  :", parent_name)
print("Student :", student_name)
print("Date    :", leave_date)
print("Reason  :", reason)
print("Status  : Pending")
print("======================================")
print("✅ Leave request submitted successfully!")

connection.close()

import sqlite3

connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()

cursor.execute("SELECT * FROM leave_requests")
requests = cursor.fetchall()

print("======================================")
print("       📝 LEAVE REQUESTS")
print("======================================")

if len(requests) == 0:
    print("No leave requests found.")
else:
    for req in requests:
        print("\nRequest ID :", req[0])
        print("Parent     :", req[1])
        print("Student    :", req[2])
        print("Leave Date :", req[3])
        print("Reason     :", req[4])
        print("Status     :", req[5])
        print("--------------------------------------")

    request_id = int(input("\nEnter Request ID to process: "))
    action = input("Enter A to Approve or R to Reject: ").upper()

    if action == "A":
        cursor.execute(
            "UPDATE leave_requests SET status = 'Approved' WHERE id = ?",
            (request_id,)
        )
        connection.commit()
        print("\n✅ Leave request approved!")

    elif action == "R":
        cursor.execute(
            "UPDATE leave_requests SET status = 'Rejected' WHERE id = ?",
            (request_id,)
        )
        connection.commit()
        print("\n❌ Leave request rejected!")

    else:
        print("\nInvalid action.")

connection.close()

import sqlite3

connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()

# Messages
cursor.execute("""
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_name TEXT,
    message TEXT,
    teacher_reply TEXT
)
""")

# Student
cursor.execute("""
CREATE TABLE IF NOT EXISTS student (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    class_name TEXT,
    attendance REAL,
    maths INTEGER,
    science INTEGER,
    english INTEGER
)
""")

# Homework
cursor.execute("""
CREATE TABLE IF NOT EXISTS homework (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject TEXT,
    homework TEXT,
    status TEXT
)
""")

# Leave Requests
cursor.execute("""
CREATE TABLE IF NOT EXISTS leave_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_name TEXT,
    student_name TEXT,
    leave_date TEXT,
    reason TEXT,
    status TEXT
)
""")

# Announcements
cursor.execute("""
CREATE TABLE IF NOT EXISTS announcements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    announcement TEXT
)
""")

# Add sample student only once
cursor.execute("SELECT COUNT(*) FROM student")

if cursor.fetchone()[0] == 0:
    cursor.execute("""
    INSERT INTO student
    (name, class_name, attendance, maths, science, english)
    VALUES (?, ?, ?, ?, ?, ?)
    """, ("Arun", "First Year", 92, 85, 88, 82))

# Add sample homework only once
cursor.execute("SELECT COUNT(*) FROM homework")

if cursor.fetchone()[0] == 0:
    cursor.execute("""
    INSERT INTO homework (subject, homework, status)
    VALUES (?, ?, ?)
    """, ("Mathematics", "Complete Chapter 3 exercises", "Pending"))

    cursor.execute("""
    INSERT INTO homework (subject, homework, status)
    VALUES (?, ?, ?)
    """, ("Science", "Prepare a short note on Plants", "Completed"))

connection.commit()
connection.close()

print("======================================")
print("   DATABASE SETUP COMPLETED ✅")
print("======================================")
print("All project tables are ready!")

import sqlite3

# Connect to database
connection = sqlite3.connect("parent_teacher_portal.db")
cursor = connection.cursor()


# ==========================================
# PARENT DASHBOARD
# ==========================================

def parent_dashboard():

    while True:

        print("\n======================================")
        print("          👨‍👩‍👦 PARENT DASHBOARD")
        print("======================================")

        print("1. View Student Performance")
        print("2. View Homework")
        print("3. Send Message to Teacher")
        print("4. Apply for Leave")
        print("5. View Announcements")
        print("6. Logout")

        choice = input("\nEnter your choice: ")

        # Student Performance
        if choice == "1":

            cursor.execute("SELECT * FROM student LIMIT 1")
            student = cursor.fetchone()

            print("\n--------- STUDENT PERFORMANCE ---------")
            print("Name       :", student[1])
            print("Class      :", student[2])
            print("Attendance :", student[3], "%")
            print("Mathematics:", student[4])
            print("Science    :", student[5])
            print("English    :", student[6])

            average = (student[4] + student[5] + student[6]) / 3
            print("Average    :", round(average, 2))


        # Homework
        elif choice == "2":

            cursor.execute("SELECT * FROM homework")
            homeworks = cursor.fetchall()

            print("\n--------- 📚 HOMEWORK ---------")

            for homework in homeworks:
                print("\nSubject :", homework[1])
                print("Task    :", homework[2])
                print("Status  :", homework[3])


        # Send Message
        elif choice == "3":

            message = input("\nEnter message to Teacher: ")

            cursor.execute("""
            INSERT INTO messages
            (parent_name, message, teacher_reply)
            VALUES (?, ?, ?)
            """, ("Parent", message, "Pending Reply"))

            connection.commit()

            print("\n✅ Message sent successfully!")


        # Leave Request
        elif choice == "4":

            student_name = input("\nEnter Student Name: ")
            leave_date = input("Enter Leave Date: ")
            reason = input("Enter Reason: ")

            cursor.execute("""
            INSERT INTO leave_requests
            (parent_name, student_name, leave_date, reason, status)
            VALUES (?, ?, ?, ?, ?)
            """, ("Parent", student_name, leave_date, reason, "Pending"))

            connection.commit()

            print("\n✅ Leave request submitted!")
            print("Status : Pending")


        # Announcements
        elif choice == "5":

            cursor.execute("SELECT * FROM announcements")
            announcements = cursor.fetchall()

            print("\n--------- 📢 ANNOUNCEMENTS ---------")

            if len(announcements) == 0:
                print("No announcements available.")

            else:
                for announcement in announcements:
                    print("-", announcement[1])


        # Logout
        elif choice == "6":

            print("\n👋 Parent logged out.")
            break

        else:
            print("\n❌ Invalid choice!")


# ==========================================
# TEACHER DASHBOARD
# ==========================================

def teacher_dashboard():

    while True:

        print("\n======================================")
        print("          👨‍🏫 TEACHER DASHBOARD")
        print("======================================")

        print("1. View Parent Messages")
        print("2. View Student Performance")
        print("3. View Leave Requests")
        print("4. Approve / Reject Leave")
        print("5. Send Announcement")
        print("6. Logout")

        choice = input("\nEnter your choice: ")


        # Parent Messages
        if choice == "1":

            cursor.execute("SELECT * FROM messages")
            messages = cursor.fetchall()

            print("\n--------- 💬 PARENT MESSAGES ---------")

            if len(messages) == 0:
                print("No messages found.")

            else:
                for msg in messages:
                    print("\nID      :", msg[0])
                    print("Parent  :", msg[1])
                    print("Message :", msg[2])
                    print("Reply   :", msg[3])


        # Student Performance
        elif choice == "2":

            cursor.execute("SELECT * FROM student LIMIT 1")
            student = cursor.fetchone()

            print("\n--------- STUDENT DETAILS ---------")
            print("Name       :", student[1])
            print("Class      :", student[2])
            print("Attendance :", student[3], "%")
            print("Mathematics:", student[4])
            print("Science    :", student[5])
            print("English    :", student[6])


        # View Leave Requests
        elif choice == "3":

            cursor.execute("SELECT * FROM leave_requests")
            requests = cursor.fetchall()

            print("\n--------- 📝 LEAVE REQUESTS ---------")

            if len(requests) == 0:
                print("No leave requests found.")

            else:
                for req in requests:
                    print("\nID         :", req[0])
                    print("Parent     :", req[1])
                    print("Student    :", req[2])
                    print("Leave Date :", req[3])
                    print("Reason     :", req[4])
                    print("Status     :", req[5])


        # Approve / Reject Leave
        elif choice == "4":

            cursor.execute("SELECT * FROM leave_requests")
            requests = cursor.fetchall()

            if len(requests) == 0:
                print("\nNo leave requests found.")

            else:

                for req in requests:
                    print("\nID:", req[0],
                          "| Student:", req[2],
                          "| Status:", req[5])

                request_id = input("\nEnter Request ID: ")
                action = input("Enter A to Approve / R to Reject: ").upper()

                if action == "A":

                    cursor.execute("""
                    UPDATE leave_requests
                    SET status = 'Approved'
                    WHERE id = ?
                    """, (request_id,))

                    connection.commit()

                    print("\n✅ Leave request approved!")

                elif action == "R":

                    cursor.execute("""
                    UPDATE leave_requests
                    SET status = 'Rejected'
                    WHERE id = ?
                    """, (request_id,))

                    connection.commit()

                    print("\n❌ Leave request rejected!")

                else:
                    print("\n❌ Invalid action!")


        # Announcement
        elif choice == "5":

            announcement = input("\nEnter Announcement: ")

            cursor.execute("""
            INSERT INTO announcements (announcement)
            VALUES (?)
            """, (announcement,))

            connection.commit()

            print("\n📢 Announcement published successfully!")


        # Logout
        elif choice == "6":

            print("\n👋 Teacher logged out.")
            break

        else:
            print("\n❌ Invalid choice!")


# ==========================================
# MAIN LOGIN
# ==========================================

while True:

    print("\n\n======================================")
    print("   🎓 PARENTS - TEACHER PORTAL")
    print("======================================")

    print("\n1. Parent Login")
    print("2. Teacher Login")
    print("3. Exit")

    role = input("\nSelect option: ")


    # Parent Login
    if role == "1":

        username = input("Username: ")
        password = input("Password: ")

        if username == "parent" and password == "1234":

            print("\n✅ Parent Login Successful!")
            parent_dashboard()

        else:
            print("\n❌ Invalid Parent Login!")


    # Teacher Login
    elif role == "2":

        username = input("Username: ")
        password = input("Password: ")

        if username == "teacher" and password == "1234":

            print("\n✅ Teacher Login Successful!")
            teacher_dashboard()

        else:
            print("\n❌ Invalid Teacher Login!")


    # Exit
    elif role == "3":

        print("\n======================================")
        print("   Thank you for using the Portal! 👋")
        print("======================================")
        break

    else:
        print("\n❌ Invalid choice!")


connection.close()